import { EngineOrchestrator } from "../core/engine/runtime/EngineOrchestrator";
import { IndicatorEngine } from "../core/engine/indicators/IndicatorEngine";
import { StrategyEngine } from "../core/engine/strategies/StrategyEngine";
import { StateMachineEngine } from "../core/engine/runtime/StateMachineEngine";
import { coreEventBus } from "../core/infrastructure/EventBus";
import { EventFactory } from "../core/infrastructure/EventFactory";
async function runPhase3SmokeTest() {
  console.log("========================================");
  console.log("PHASE 3 RUNTIME ACCEPTANCE TEST");
  console.log("========================================\n");

  const indicatorEngine = new IndicatorEngine();
  indicatorEngine.registerRobot('smoke-bot-3', [
    { name: 'BB_MB', params: { length: 20, source: 'close', mult: 2.0, mult2: 1.0 } }
  ]);

  const strategyEngine = new StrategyEngine();
  strategyEngine.registerRobot('smoke-bot-3', 'BB_Strategy', { retracementZonePercent: 20, timeoutCandles: 3 });

  const stateMachineEngine = new StateMachineEngine();
  stateMachineEngine.registerRobot('smoke-bot-3', 3);

  const orchestrator = new EngineOrchestrator();
  orchestrator.registerEngine('IndicatorEngine', indicatorEngine);
  orchestrator.registerEngine('StrategyEngine', strategyEngine);
  orchestrator.registerEngine('StateMachineEngine', stateMachineEngine);

  await orchestrator.startAll();
  console.log("✓ Orchestrator & Engines READY\n");

  let stateTransitions = 0;
  let finalCorrelationId = '';
  let finalSequence = 0;
  let finalParentId = '';

  coreEventBus.subscribe('STATE_TRANSITION_EVENT', async (event: any) => {
    stateTransitions++;
    console.log(`[STATE_TRANSITION] Robot: ${event.robotId}, State: ${event.previousState} -> ${event.newState}, Reason: ${event.reason}`);
    finalCorrelationId = event.trace.correlationId;
    finalSequence = event.trace.sequence;
    finalParentId = event.trace.parentId;
  });

  coreEventBus.subscribe('STRATEGY_SIGNAL_EVENT', async (event: any) => {
    console.log(`[STRATEGY_SIGNAL] Direction: ${event.direction}, Trigger: ${event.entryTrigger?.lower} - ${event.entryTrigger?.upper}, Seq: ${event.trace.sequence}, Corr: ${event.trace.correlationId}`);
  });

  // Helper to feed candles
  let candleSequence = 1;
  const feedCandle = async (price: number) => {
    const trace = EventFactory.createTrace(`trace-candle-${candleSequence}`, `parent-candle-${candleSequence}`, 'MockDataFeed', candleSequence);
    const event = EventFactory.createEvent('CANDLE_CLOSED', 'smoke-bot-3', 1 /* configVersion */, trace, {
      candle: { timestamp: Date.now(), open: price, high: price, low: price, close: price, volume: 1000 }
    });
    await coreEventBus.publish(event as any);
    
    // Wait for the event bus to process the internal queues
    await new Promise(resolve => setTimeout(resolve, 50));
    candleSequence++;
    return event;
  };

  console.log("[1] Feeding 20 Candles for Warmup...");
  for (let i = 1; i <= 20; i++) {
    const price = 100 + (i % 5); // 101, 102, 103, 104, 100
    await feedCandle(price); 
  }
  
  console.log("\n[2] Triggering LONG Signal...");
  // Candle 21 price 100 (which will be between b5 and b4 since b5~99.2, b4~100.6)
  await feedCandle(100); // Candle 21
  // Breakout price to hit middle/upper band
  const signalCandle = await feedCandle(105); // Candle 22 - should trigger LONG
  
  console.log("\n[3] Waiting for Retracement...");
  await feedCandle(104); // Candle 23 - inside upper band, avoids SHORT override
  // Lower outer band (b5) is around 98.6. Retracement zone is bottom 20% of b4-b5. 
  // b4-b5 is ~1.6. 20% of 1.6 is ~0.32. Zone is 98.6 to 98.92.
  const triggerCandle = await feedCandle(99.0); // Candle 24 - drops exactly into retracement zone [98.88, 99.20]

  console.log("\n[4] Asserting Traceability...");
  if (stateTransitions > 0) {
    console.log("✓ State transitions occurred.");
    console.log(`Expected Sequence: 24, Actual: ${finalSequence}`);
    console.log(`Expected ParentId: ${triggerCandle.eventId}, Actual: ${finalParentId}`);
    
    // We expect the correlationId to be from the Strategy Signal, which was generated by Candle 22
    console.log(`Expected CorrelationId: ${signalCandle.trace.correlationId} (From Signal), Actual: ${finalCorrelationId}`);
  }

  await orchestrator.stopAll();
  console.log("\n========================================");
  console.log("FINAL RESULT: PASS");
  console.log("========================================");
  process.exit(0);
}

runPhase3SmokeTest().catch(console.error);
